### ISSUE TITLE
/usr/bin/ld: cannot find -l:sourcekitdInProc

### ISSUE THREAD

**Issue by pluckytree** [jinmingjian/sourcekite#3]
Probably user error but I've not been able to get around a problem I'm having building your project. Here's the setup:

1. Ubuntu 16.04 LTS on Raspberry Pi3
2. Swift 3.0.2 installed in /home/pi/swift-sources
3. Swift Package Manager builds test project: https://github.com/miles3898/spm-example
4. Swift can build, compile, and run projects
5. I cloned sourcekite
6. I set up the symlink, but also set one up in my Swift source directory

sudo ln -s /usr/lib/sourcekitdInProc.framework/sourcekitdInProc /usr/lib/sourcekitdInProc
sudo ln -s /home/pi/swift-source/usr/lib/sourcekitdInProc.framework/sourcekitdInProc /home/pi/swift-source/usr/lib/sourcekitdInProc

7. When I run the build command, though, this is what happens:

pi@cricketpi:~/projects/sourcekite$ swift build -Xlinker -l:sourcekitdInProc
Linking sourcekitd
/usr/bin/ld: cannot find -l:sourcekitdInProc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/pi/swift-root/usr/bin/swift-build-tool -f /home/pi/projects/sourcekite/.build/debug.yaml

Perhaps a problem with the linker, but it seems to be working otherwise. Ideas?

**Comment by pluckytree** [comment]
Sorry, I missed the existing closed issue, thanks.

**Comment by jinmingjian** [comment]
@pluckytree still thanks for report:) Basically, Swift 3.0.x is not supported because the SDE is using _"swift package describe"_ to discovery the metadata of a SPM project which is new in the 3.1 train.
